/**
 * GET   /api/plan?tz=      — today's plan timeline (seeds/fills additively).
 * POST  /api/plan          — add a user-defined item to today's plan.
 * PATCH /api/plan          — update a plan item's status.
 * DELETE /api/plan?id=     — remove a plan item.
 *
 * Backs the redesign-v3 "Today's plan" timeline (see docs/redesign-v3-plan.md
 * Phase 2). Rows live in `plan_items`, keyed by (user, local calendar day) —
 * see `lib/localDay.ts` for the day-key convention, same one `/api/today`
 * uses for the diet budget.
 *
 * Seeding (GET only): plan rows are never bulk-generated by an LLM call on
 * this route. Instead, every GET additively inserts:
 *   - a "Lights out" sleep item (once — skipped if a same-titled row already
 *     exists for today), and
 *   - any meal from the *cached* daily brief (`getCachedBrief` — never
 *     awaits/triggers a fresh Claude call) whose title isn't already present
 *     for today.
 * This means the plan may show only "Lights out" on the very first GET of
 * the day (before the brief has finished generating in the background via
 * /api/today) and fills in meals on a subsequent GET once the brief lands —
 * no polling needed beyond the client's normal refresh cadence.
 *
 * Status is server-tracked as pending/done/skipped only — now/next/later is
 * a client-side, clock-derived display concern (see TodayViewModel).
 *
 * GET response: { items: [{ id, timeMinutes, title, subtitle, kind, source,
 *                            status, kcal }] }  (sorted by timeMinutes)
 * POST body:    { timeMinutes, title, subtitle?, kind, kcal? } → created item
 * PATCH body:   { id, status } (status ∈ pending/done/skipped) → updated item
 * DELETE query: ?id=
 *
 * Auth: session JWT via middleware → x-user-id, read with getUserIdFromRequest.
 */

import { NextResponse } from 'next/server';
import { db, schema } from '@/db';
import { eq, and } from 'drizzle-orm';
import { getUserIdFromRequest } from '@/lib/auth';
import { getCachedBrief, briefCacheKey } from '@/lib/brain/briefCache';
import { localDayKey, pickTimeZone } from '@/lib/localDay';

export const dynamic = 'force-dynamic';

const VALID_KINDS = ['meal', 'move', 'rest', 'sleep', 'other'];
const VALID_STATUSES = ['pending', 'done', 'skipped'];

// Heuristic meal times — mirrors TodayViewModel's Phase 1 derivation
// (ios/Vital/Sources/Features/Today/TodayViewModel.swift) exactly, so a plan
// item's time doesn't jump once the client switches from local derivation to
// this server-seeded row.
const BREAKFAST_MIN = 8 * 60;        // 480 — 8:00
const LUNCH_MIN     = 12 * 60 + 45;  // 765 — 12:45
const DINNER_MIN    = 19 * 60 + 30;  // 1170 — 19:30
const LIGHTS_OUT_MIN = 22 * 60 + 30; // 1350 — 22:30

type BriefMeal = { name: string; kcal: number; why: string };
type MealSlot = 'breakfast' | 'lunch' | 'dinner' | 'unmatched';

function mealSlot(name: string): MealSlot {
  const lower = name.toLowerCase();
  if (lower.includes('breakfast') || lower.includes('oat') || lower.includes('egg')) return 'breakfast';
  if (lower.includes('lunch') || lower.includes('chicken') || lower.includes('bowl')) return 'lunch';
  if (lower.includes('dinner') || lower.includes('salmon') || lower.includes('pasta')) return 'dinner';
  return 'unmatched';
}

/** Maps each brief meal name to a heuristic time-of-day, matching the iOS derivation. */
function heuristicMealTimes(plan: BriefMeal[]): Map<string, number> {
  const times = new Map<string, number>();
  const unmatched = plan.filter(item => mealSlot(item.name) === 'unmatched');
  unmatched.forEach((item, index) => {
    const fraction = (index + 1) / (unmatched.length + 1);
    times.set(item.name, LUNCH_MIN + Math.round((DINNER_MIN - LUNCH_MIN) * fraction));
  });
  for (const item of plan) {
    switch (mealSlot(item.name)) {
      case 'breakfast': times.set(item.name, BREAKFAST_MIN); break;
      case 'lunch':      times.set(item.name, LUNCH_MIN); break;
      case 'dinner':     times.set(item.name, DINNER_MIN); break;
      case 'unmatched':  break; // already set above
    }
  }
  return times;
}

function serialize(row: typeof schema.plan_items.$inferSelect) {
  return {
    id:          row.id,
    timeMinutes: row.time_minutes,
    title:       row.title,
    subtitle:    row.subtitle,
    kind:        row.kind,
    source:      row.source,
    status:      row.status,
    kcal:        row.kcal,
  };
}

/**
 * Resolves today's local-day key for a request: prefers a fresh `?tz=` query
 * param (device's current zone), else the user's stored timezone, else UTC —
 * same precedence `/api/today` uses. Doesn't persist the tz itself; /api/today
 * already does that on every load and the iOS client always calls both
 * concurrently, so the stored value is fresh by the time POST/PATCH/DELETE run.
 */
async function resolveDayKey(request: Request, userId: string): Promise<string> {
  const paramTz = new URL(request.url).searchParams.get('tz');
  const [userRow] = await db.select().from(schema.users).where(eq(schema.users.id, userId)).limit(1);
  const tz = pickTimeZone(paramTz, userRow?.timezone);
  return localDayKey(new Date(), tz);
}

// ── GET ──────────────────────────────────────────────────────────────────────

export async function GET(request: Request): Promise<NextResponse> {
  let userId: string;
  try {
    userId = getUserIdFromRequest(request);
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 401 });
  }

  const dayKey = await resolveDayKey(request, userId);

  let rows = await db
    .select()
    .from(schema.plan_items)
    .where(and(eq(schema.plan_items.user_id, userId), eq(schema.plan_items.local_day, dayKey)));

  const existingTitles = new Set(rows.map(r => r.title));
  const toInsert: (typeof schema.plan_items.$inferInsert)[] = [];

  if (!existingTitles.has('Lights out')) {
    toInsert.push({
      user_id:      userId,
      local_day:    dayKey,
      time_minutes: LIGHTS_OUT_MIN,
      title:        'Lights out',
      subtitle:     '8h target',
      kind:         'sleep',
      source:       'coach',
      status:       'pending',
      kcal:         null,
    });
  }

  const cached = getCachedBrief(briefCacheKey(userId, dayKey));
  if (cached) {
    const times = heuristicMealTimes(cached.plan);
    for (const meal of cached.plan) {
      if (existingTitles.has(meal.name)) continue;
      existingTitles.add(meal.name); // guards against duplicate names within the same brief
      const subtitle = meal.why ? `${meal.why} · ${meal.kcal} kcal` : `${meal.kcal} kcal`;
      toInsert.push({
        user_id:      userId,
        local_day:    dayKey,
        time_minutes: times.get(meal.name) ?? LUNCH_MIN,
        title:        meal.name,
        subtitle,
        kind:         'meal',
        source:       'coach',
        status:       'pending',
        kcal:         Math.round(meal.kcal),
      });
    }
  }

  if (toInsert.length > 0) {
    const inserted = await db.insert(schema.plan_items).values(toInsert).returning();
    rows = [...rows, ...inserted];
  }

  const items = rows.map(serialize).sort((a, b) => a.timeMinutes - b.timeMinutes);

  return NextResponse.json({ items });
}

// ── POST ─────────────────────────────────────────────────────────────────────

export async function POST(request: Request): Promise<NextResponse> {
  let userId: string;
  try {
    userId = getUserIdFromRequest(request);
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 401 });
  }

  let body: Record<string, unknown>;
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body.' }, { status: 400 });
  }

  const { timeMinutes, title, subtitle, kind, kcal } = body;

  if (typeof timeMinutes !== 'number' || !Number.isFinite(timeMinutes)) {
    return NextResponse.json({ error: 'timeMinutes must be a number.' }, { status: 400 });
  }
  if (typeof title !== 'string' || title.trim().length === 0) {
    return NextResponse.json({ error: 'title is required.' }, { status: 400 });
  }
  if (typeof kind !== 'string' || !VALID_KINDS.includes(kind)) {
    return NextResponse.json({ error: `kind must be one of ${VALID_KINDS.join(', ')}.` }, { status: 400 });
  }
  if (subtitle !== undefined && subtitle !== null && typeof subtitle !== 'string') {
    return NextResponse.json({ error: 'subtitle must be a string.' }, { status: 400 });
  }
  if (kcal !== undefined && kcal !== null && typeof kcal !== 'number') {
    return NextResponse.json({ error: 'kcal must be a number.' }, { status: 400 });
  }

  const dayKey = await resolveDayKey(request, userId);

  const [inserted] = await db
    .insert(schema.plan_items)
    .values({
      user_id:      userId,
      local_day:    dayKey,
      time_minutes: Math.round(timeMinutes),
      title:        title.trim(),
      subtitle:     (subtitle as string | null | undefined) ?? null,
      kind,
      source:       'user',
      status:       'pending',
      kcal:         kcal != null ? Math.round(kcal as number) : null,
    })
    .returning();

  return NextResponse.json(serialize(inserted));
}

// ── PATCH ────────────────────────────────────────────────────────────────────

export async function PATCH(request: Request): Promise<NextResponse> {
  let userId: string;
  try {
    userId = getUserIdFromRequest(request);
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 401 });
  }

  let body: Record<string, unknown>;
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body.' }, { status: 400 });
  }

  const { id, status } = body;

  if (typeof id !== 'string' || id.length === 0) {
    return NextResponse.json({ error: 'id is required.' }, { status: 400 });
  }
  if (typeof status !== 'string' || !VALID_STATUSES.includes(status)) {
    return NextResponse.json({ error: `status must be one of ${VALID_STATUSES.join(', ')}.` }, { status: 400 });
  }

  const [updated] = await db
    .update(schema.plan_items)
    .set({ status, updated_at: new Date() })
    .where(and(eq(schema.plan_items.id, id), eq(schema.plan_items.user_id, userId)))
    .returning();

  if (!updated) {
    return NextResponse.json({ error: 'Plan item not found.' }, { status: 404 });
  }

  return NextResponse.json(serialize(updated));
}

// ── DELETE ───────────────────────────────────────────────────────────────────

export async function DELETE(request: Request): Promise<NextResponse> {
  let userId: string;
  try {
    userId = getUserIdFromRequest(request);
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 401 });
  }

  const id = new URL(request.url).searchParams.get('id');
  if (!id) {
    return NextResponse.json({ error: 'id query param is required.' }, { status: 400 });
  }

  const [deleted] = await db
    .delete(schema.plan_items)
    .where(and(eq(schema.plan_items.id, id), eq(schema.plan_items.user_id, userId)))
    .returning();

  if (!deleted) {
    return NextResponse.json({ error: 'Plan item not found.' }, { status: 404 });
  }

  return NextResponse.json({ ok: true });
}
