/**
 * Vital Brain — in-memory brief cache
 *
 * The daily brief (insight + meal plan) is generated by Claude and takes
 * 15–27s, far too slow to block the /api/today response. This module caches
 * the derived { insight, plan } per (userId, YYYY-MM-DD) so the first request
 * of the day warms the cache in the background and every subsequent request
 * returns it instantly.
 *
 * Scope: dev only. A module-level Map is sufficient for a single-process dev
 * server. In production (serverless, multi-instance) this would move to Redis
 * or a Postgres table — out of scope for now.
 *
 * The Map is attached to globalThis so Next.js HMR doesn't blow it away on
 * every hot reload during development.
 */

export interface CachedBrief {
  insight: string;
  plan: Array<{ name: string; kcal: number; why: string }>;
}

const g = globalThis as typeof globalThis & {
  _vitalBriefCache?: Map<string, CachedBrief>;
};

const cache: Map<string, CachedBrief> = g._vitalBriefCache ?? new Map();
if (process.env.NODE_ENV !== 'production') {
  g._vitalBriefCache = cache;
}

/** Build the cache key for a user + UTC date (YYYY-MM-DD). */
export function briefCacheKey(userId: string, date: string): string {
  return `${userId}:${date}`;
}

/** Today's UTC date as YYYY-MM-DD — the canonical key suffix. */
export function todayKey(): string {
  return new Date().toISOString().split('T')[0];
}

export function getCachedBrief(key: string): CachedBrief | undefined {
  return cache.get(key);
}

export function setCachedBrief(key: string, value: CachedBrief): void {
  cache.set(key, value);
}
